### ISSUE TITLE
Only the first layer is recognized if multiple layers was added

### ISSUE THREAD

**Issue by lgoltz** [opengeospatial/ets-wms-client13#34] opened 2018-02-01 12:33 UTC
The test engine seems to parse only the first layer in a GetMap request. Because of this I have to toggle each layer visibility individually for the parser to recognize the requests being sent.

**Comment by lgoltz** [comment] 2018-03-01 08:55
Problem is reproducible with FF 58.0.2 (Ubuntu Linux 17.10) and the following request:

http://localhost:8081/teamengine/monitor/4?SERVICE=WMS&VERSION=1.3.0&REQUEST=GetMap&BBOX=-1,-2,6,2&CRS=EPSG:4326&WIDTH=352&HEIGHT=614&LAYERS=cite:Autos,cite:BasicPolygons,cite:Bridges,cite:BuildingCenters,cite:Buildings,cite:DividedRoutes,cite:Forests,cite:Lakes,cite:MapNeatline,cite:NamedPlaces,cite:Ponds,cite:RoadSegments,cite:Streams&STYLES=&FORMAT=image/png&DPI=96&MAP_RESOLUTION=96&FORMAT_OPTIONS=dpi:96&TRANSPARENT=TRUE

**Comment by keshavnangare** [comment] 2018-06-14 04:43
The only one layer is recognized by the teamengine even if the multiple layers in a request.

I have investigated theQGIS is not sending the multiple layers in single request so to process the layer we need to toggle each layer.

Also I have tested the Udig tool, the Udig is supporting the multiple layers in single request so may the problem is with the Qgis tool.

The teamengine is able to process this request and able to changes the status in the result page.

@lgoltz 

Do we have different way to handle this situation?

**Comment by dstenger** [comment] 2018-06-20 08:24
@keshav-nangare 

Can you investigate what requests the tool QGIS and Udig are sending and document the results here?

**Comment by keshavnangare** [comment] 2018-06-26 12:42
@dstenger 

I have investigated the QGIS and Udig tool and following are the results:

- QGIS:
         The QGIS sending the single request even if we selected the multiple layers.
         Requests:  
         [1] Selected the two layers cite:Autos and cite:BasicPolygon: http://localhost:8080/teamengine/monitor/7?SERVICE=WMS&VERSION=1.3.0&REQUEST=GetMap&BBOX=-0.002200000000000000133,-0.003200000000000000153,0.002200000000000000133,0.0028999999999999998&CRS=EPSG:4326&WIDTH=779&HEIGHT=561&LAYERS=cite:Autos&STYLES=&FORMAT=image/png&DPI=96&MAP_RESOLUTION=96&FORMAT_OPTIONS=dpi:96&TRANSPARENT=TRUE
         [2] Three layers are selected cite:NamedPlacess, cite:Ponds and cite:RoadSegments: http://localhost:8080/teamengine/monitor/7?SERVICE=WMS&VERSION=1.3.0&REQUEST=GetMap&BBOX=-0.002000000000000000042,-0.004000000000000000083,0.002000000000000000042,0.004000000000000000083&CRS=EPSG:4326&WIDTH=1021&HEIGHT=511&LAYERS=cite:RoadSegments&STYLES=&FORMAT=image/png&DPI=96&MAP_RESOLUTION=96&FORMAT_OPTIONS=dpi:96&TRANSPARENT=TRUE HTTP/1.1


- Udig:
         The Udig is supporting the multiple layers in single request.
         Request:
         [1] Three Layers are selected: http://localhost:8080/teamengine/monitor/7?SERVICE=WMS&LAYERS=cite%3APonds,cite%3ARoadSegments,cite%3ANamedPlaces&CRS=CRS:84&FORMAT=image/png&HEIGHT=522&TRANSPARENT=TRUE&REQUEST=GetMap&BBOX=-0.004,-0.002,0.004,0.002&WIDTH=1044&STYLES=Ponds,RoadSegments,NamedPlaces&VERSION=1.3.0

**Comment by dstenger** [comment] 2018-09-05 08:06
After https://github.com/opengeospatial/ets-wms-client13/pull/40 will have been merged, the reported behaviour should be tested again (with QGIS and Udig).

**Comment by keshavnangare** [comment] 2019-10-18 07:13
@dstenger 

I have tested the reported behavior with QGIS & Udig tool and all the added layers are recognized.
If we add the multiple layers or single layer all are processed and updating the status on the teamengine page.

**Comment by lgoltz** [comment] 2020-01-07 12:30
Works fine now. Tested with
1. http://localhost:8081/teamengine/monitor/0?SERVICE=WMS&REQUEST=GetCapabilities
2. http://localhost:8081/teamengine/monitor/1?SERVICE=WMS&VERSION=1.3.0&REQUEST=GetMap&BBOX=-7,-5.840116279069768268,7,7&CRS=EPSG:4326&WIDTH=451&HEIGHT=492&LAYERS=cite:Bridges,cite:BasicPolygons,cite:Forests,cite:Lakes&STYLES=&FORMAT=image/png&DPI=96&MAP_RESOLUTION=96&FORMAT_OPTIONS=dpi:96&TRANSPARENT=TRUE
    * Requested layers are marked as requested in the ets.

**Closed as completed** 2020-01-07 12:30 UTC
Labels: enhancement
